[build]
  publish = "frontend"
  command = ""

[[redirects]]
  from = "/_api/*"
  to = "https://agendamento-banco-de-dados.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
