[phases.setup]
nixPkgs = [
    "python311Full",  # versão completa com pip
    "gcc",
    "gnumake",
    "zlib",
    "libjpeg",
    "freetype",
    "libpng",
    "pkg-config"
]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",   # garante pip instalado
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8000}"
