[phases.setup]
# Pacotes do sistema que o backend precisa
nixPkgs = [
    "python311",      # Python 3.11
    "gcc",            # compilador C
    "gnumake",        # make
    "zlib",           # compressão (Pillow, reportlab)
    "libjpeg",        # imagens JPEG (Pillow)
    "freetype",       # fontes (matplotlib, reportlab)
    "libpng",         # imagens PNG (Pillow, matplotlib)
    "pkg-config"      # ajuda na detecção de libs
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
# Ajuste para o nome do seu arquivo principal
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8000}"
